### ISSUE TITLE
The validator should probably ignore punctuation at the beginning and end of the original language quote

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#574] opened 2020-12-08 20:46 UTC
v1.1.0 (develop)
Not a big deal, but the double quote is not really the beginning of a word.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/bce884ec-e96f-46ef-aea1-df9ec6388677)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/60111773-e48c-4078-bc64-d3d0445c8f60)

**Comment by RobH123** [comment] 2020-12-09 20:00
Ah, is that a " straight quote? So this is a consequential error. Presumably there's another error for that line mentioning the bad quote character. But I'll fix the 620 error to ignore that.

**Comment by cckozie** [comment] 2020-12-09 21:47
Here's a similar one for 621 error in Romans. The target original quote is \u1f40\u03be\u03b5\u1fd6\u03c2 \u03bf\u1f31 \u03c0\u03cc\u03b4\u03b5\u03c2 \u03b1\u1f50\u03c4\u1ff6\u03bd\u002c \u1f10\u03ba\u03c7\u03ad\u03b1\u03b9 \u03b1\u1f37\u03bc\u03b1. Is it the ellipsis in the original text that is causing the problem?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c1c5c732-1fc5-426f-b48f-7f66b3e3207b)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/07432309-d1ae-488c-a43f-2d6011e3d157)

**Comment by birchamp** [comment] 2020-12-15 15:29
@cckozie Do you know if tC ignores the punctuation?

**Comment by cckozie** [comment] 2020-12-15 16:52
@birchamp - It looks like tC is somewhat inconsistent in relation to highlighting punctuation at the start or end of the snippet.
And as noted elsewhere, the original language snippet highlighting sometimes varies between tC and tC Create.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/d89ef8d9-4a45-4bcd-b131-b39564bea820)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/6e9d6895-6aa0-4b4a-b8b7-b3b5f23f9bf8)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a95d6ac2-65db-4257-a922-133fb220ebb1)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/58c640eb-a630-415b-b668-726ee5d6df13)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c36d0f6b-8e28-44b3-bdc7-c4446c01f2a9)

**Comment by cckozie** [comment] 2020-12-29 16:01
Similar issue exists when the quote ends with an ellipsis. e.g. Romans line 227
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/2877d1a3-d351-4434-bdd4-b04586d27c81)

**Comment by birchamp** [comment] 2021-01-06 15:36
@RobH123 @cckozie Could we compromise on this by reducing the priority number?

**Comment by cckozie** [comment] 2021-01-06 19:01
@birchamp - I haven't done an extensive check of all places this error is identified, but I only remember seeing this error show up when it is a situation the user probably is not going to change. In general, I think we should not report things as errors that the user does not want to fix and would rather not see. 
If you show me some use cases where the user may regard this as an error that they actually would want to fix, that may cause me to change my view.

**Comment by birchamp** [comment] 2021-01-12 16:25
@RobH123 can you give us an example here?

**Comment by RobH123** [comment] 2021-01-12 23:53
As mentioned above, I think this was a consequential error resulting from not using the correct quote marks. And I think I fixed the CV package about a month ago to prevent that. But I'm not sure what needs to be done now to confirm that with a passing test? Was the initial test something than can be replicated now @cckozie ?

**Comment by cckozie** [comment] 2021-01-13 22:46
@RobH123 - In tC Create v1.1.0-rc3 the validator does not report any 620 errors on any New Testament book. It is still reporting 621 errors when the snippet is followed by a hyphen or ellipsis (may be others too). Romans is currently showing three 621 errors.

**Comment by RobH123** [comment] 2021-01-13 23:54
Ah, I think I see now @cckozie: This issue covers two different errors and I only fixed one (consequential 620 error due to invalid " straight quote mark at beginning of word). But I didn't realise that the UGNT contains FOUR eliipsis characters and will first check with the content team to make sure that they're not outliers before changing the checking code.

**Comment by RobH123** [comment] 2021-01-14 18:06
Ok, Alan Bunning confirmed that the four ellipsis characters in the UGNT are iindeed ntentional. This bug will be fixed in uw-content-validator v1.0.2. Thanks for catching it @cckozie .

**Comment by cckozie** [comment] 2021-02-22 17:27
It appears that this have been fixed in v1.1.0. I am no longer seeing the 620 error in Luke or the 621 error in Romans.

**Comment by birchamp** [comment] 2021-03-02 19:49
This was fixed by unfoldingWord/uw-content-validation#128 and unfoldingWord/uw-content-validation#68

**Closed** 2021-03-02 19:50 UTC
