### ISSUE TITLE
Integrate the new & ampersand code from scripture resources RCL into tC Create

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1409] opened 2022-10-24 13:09 UTC
Work on making the code for gEdit that's in the shared RCL work for tC Create - without breaking gatewayEdit. 

DoD:
---
Ampersand can be used instead of the ellipsis for highlighting discontiguous words

**Comment by elsylambert** [comment] 2022-11-15 01:50
I do not see this in translationCore Create - v1.7.1 build 179-d617b89. Has the PR been merged? @jincypjose 
![Screenshot 2022-11-14 at 8.48.18 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/bbcbd5ba-23f6-42d1-8e15-b0a7204369d2)

**Comment by jincypjose** [comment] 2022-11-15 10:12
The version was not updated in tc Create. Now it is
Build Number is 181-a4f40e9![Screenshot from 2022-11-15 15-41-16.png](https://images.zenhubusercontent.com/5f8fb2e83cdc9276e3df86d3/166a3a74-3512-49ef-82ac-32e447d9b0d5) Now the result using & is like this

**Comment by jincypjose** [comment] 2022-11-15 15:54
As discussed with @birchamp 
jincypjose
 — 
Today at 8:31 PM
I have a question for https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/1409 (the issue is regarding ampersand). We just need to handle the ampersand when we type in or should all  the ellipsis be replaced with ampersand?
Zenhub
Zenhub
Zenhub | Productivity Management for Software Teams
This is just to make myself clear for the issue.
Birch
 — 
Today at 8:44 PM
You don't need to replace the ellipsis. Just parse both the same way.

**Comment by elsylambert** [comment] 2022-11-17 14:40
Blocked by #1442 as the highlighting is broken post TSV7 conversion.

**Comment by elsylambert** [comment] 2022-11-18 18:23
Looks good and works fine in translationCore Create - v1.8 build 183-ca725ce. & in Original Quote is highlighted properly.
![Screenshot 2022-11-18 at 1.21.17 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d1762148-d672-44f4-928c-1b85cbbc696d)

**Closed** 2022-12-12 13:56 UTC
Labels: QA/Passed
