### ISSUE TITLE
Validator reports "Unable to find original language quote in verse text" even though tC Create shows it highlighted

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#572] opened 2020-12-08 16:46 UTC
**DOD** (after much collaboration)
**Zero width spaces are stripped from the beginning and end of each cell in the in-memory data so that the validator does not report such situations as errors.**

 v1.1.0 (develop)
There must be something different in what the validator is check for vs what tC Create is looking for when comparing the original quote filed to the original language text. 
UTF of word in original quote: \u03b5\u1f50\u03c3\u03ad\u03b2\u03b5\u03b9\u03b1\u03bd\u200b
UTF of word in UGNT:              \u03b5\u1f50\u03c3\u03ad\u03b2\u03b5\u03b9\u03b1\u03bd

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/114f1a49-1c2a-4e82-8ce7-7cd807a93bc1)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/6a6a8dd7-2ad3-41ad-9116-c70b6c1e680c)

**Comment by RobH123** [comment] 2020-12-09 18:54
On a separate matter, I'm curious why excerpt shows undefined for those two rows (unexpected), but blank for others (expected). Presumably that's a fault in the CV package, although I couldn't find an obvious bug. But hard to envisage how it could be a bug in the app???

**Comment by RobH123** [comment] 2020-12-09 19:50
What version of the CV package is this using? I couldn't replicate those errors [here](https://unfoldingword.github.io/uw-content-validation/#/Book%20Package%20Checker%20Demo?id=bookpackagecheck), including the above trying to load a Greek verse for front:intro which doesn't even have a OrigQuote. Admittedly that demo link uses the latest CV package (in progress) and the latest content files, so it's not an identical test. But I can't find anything to fix.

**Comment by cckozie** [comment] 2020-12-17 22:32
I'm seeing the same problem in the project at: https://qa.door43.org/translate_test/en_tn/src/branch/tc01-tc-create-1/en_tn_15-EZR.tsv

tsv text file here: [https://app.zenhub.com/files/191973535/c53dd36a-9663-436f-8aed-0a5c6b92a95b/download](https://app.zenhub.com/files/191973535/c53dd36a-9663-436f-8aed-0a5c6b92a95b/download)

The validator reports lots of priority 913 errors, but I don't see any difference in the unicode characters comparing the highlighted snippet in the original to the target original quote. This is the data from ID 3th4:
Highlighted Greek snippet [וּ⁠בִ⁠שְׁנַ֣ת אַחַ֗ת לְ⁠כ֨וֹרֶשׁ֙ מֶ֣לֶךְ פָּרַ֔ס]: 
\u05d5\u05bc\u2060\u05d1\u05b4\u2060\u05e9\u05c1\u05b0\u05e0\u05b7\u05a3\u05ea \u05d0\u05b7\u05d7\u05b7\u0597\u05ea \u05dc\u05b0\u2060\u05db\u05a8\u05d5\u05b9\u05e8\u05b6\u05e9\u05c1\u0599 \u05de\u05b6\u05a3\u05dc\u05b6\u05da\u05b0 \u05e4\u05bc\u05b8\u05e8\u05b7\u0594\u05e1

Target OrigQuote [וּ⁠בִ⁠שְׁנַ֣ת אַחַ֗ת לְ⁠כ֨וֹרֶשׁ֙ מֶ֣לֶךְ פָּרַ֔ס]:
\u05d5\u05bc\u2060\u05d1\u05b4\u2060\u05e9\u05c1\u05b0\u05e0\u05b7\u05a3\u05ea \u05d0\u05b7\u05d7\u05b7\u0597\u05ea \u05dc\u05b0\u2060\u05db\u05a8\u05d5\u05b9\u05e8\u05b6\u05e9\u05c1\u0599 \u05de\u05b6\u05a3\u05dc\u05b6\u05da\u05b0 \u05e4\u05bc\u05b8\u05e8\u05b7\u0594\u05e1

**Comment by birchamp** [comment] 2021-01-06 15:33
@mandolyte @RobH123 Can you give some insight as to what's happening here?

**Comment by mandolyte** [comment] 2021-01-08 14:07
Unable to replicate at this point (lots has changed since this was originally written). At present, there are no high priority notices at all in the book of Titus.

@birchamp @cckozie -- suggest we close this one.

**Comment by birchamp** [comment] 2021-01-12 15:51
@cckozie do you want to retest this before we close it?

**Comment by cckozie** [comment] 2021-01-12 18:06
Still seeing in v1.1.0-rc.3
The project is at https://qa.door43.org/translate_test/en_tn/src/branch/tcc001-tc-create-1/en_tn_57-TIT.tsv
Note the highlighting in ID xyz8
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/3d874efc-ba5e-4524-ada3-d3dd522dd485)

And the validation error on that row (the zero-width space error is new, so maybe that is the problem.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/1d3f93ef-db59-4f6e-b948-d84643e77a05)

**Comment by mandolyte** [comment] 2021-01-13 18:39
@ancientTexts-net  @cckozie Looking at this and found the following:
- If you bring up the file fresh and add ID original quote
- Go to that row (xyz8)
- Click at the end of the string εὐσέβειαν
- Then a click of left arrow arrow one time appears to do nothing; if you do it a second time it does
- So there is a zws at the end of the string just like the validator reports
- However as soon as you click out of the field, the zws is removed. So the on blur is causing the data to be re-rendered.
- Furthermore, if you do the on-blur and run validator the notice will not be there.

How did I know where the zws was? On the preceding line in the validator reports is the notice that there is a zws present. In the "Excerpt" column is this: …σέβειαν‼

The two exclamation points indicate the location of the zwp.

![image](https://user-images.githubusercontent.com/1289437/104493908-bcc52900-55a3-11eb-85e9-9800f4d0bbb1.png)

Finally, if I do the above steps but go out of preview mode into markdown, I will find the same zws in the real, raw data. However, in markdown, this zws does NOT go away if you click out (on blur).

@ancientTexts-net Where is the code you had to filter for these zws characters? Isn't it in markdown-translatable? Looking...

**Comment by ancientTexts-net** [comment] 2021-01-14 15:52
Compare, see:

https://github.com/unfoldingWord/markdown-translatable/pull/40/files


@mandolyte

**Comment by cckozie** [comment] 2021-01-27 21:28
I am still seeing this problem in v1.1.0-rc.4 build 18-e095e04. The zws does not appear in the string when I copy from tCC (in either preview or md mode) and paste into a unicode converter.
![image](https://user-images.githubusercontent.com/8171759/106055219-b611d800-60b2-11eb-9ed4-c211502e2264.png)

![image](https://user-images.githubusercontent.com/8171759/106055308-d04bb600-60b2-11eb-9cd0-c1ab1e563f48.png)

**Comment by RobH123** [comment] 2021-01-27 21:43
Am I being waited on to contribute in this thread? Have you run your source file through the [Content Validator demo](http://localhost:6060/#/File%20Checker%20Demo?id=filecheck)? Do you think it's giving false alarms? (I'm having trouble reading between the lines above to see what people are thinking is the problem.)

**Comment by ancientTexts-net** [comment] 2021-01-27 23:09
@RobH123 @cckozie 

I believe the current thinking is that tC Create is adding the NBSP

**Comment by ancientTexts-net** [comment] 2021-01-27 23:09
@RobH123 Thank you

**Comment by ancientTexts-net** [comment] 2021-01-27 23:20
Thank you @cckozie 

Did you create this TSV in version `v1.1.0-rc.4 build 18-e095e04` please?
or is it a remnant from a prior version?

Thank you

**Comment by ancientTexts-net** [comment] 2021-01-27 23:20
I ask this because I am unable to reproduce

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/d0e95a38-c3f0-4530-b1d4-5eb132f035c7)

**Comment by cckozie** [comment] 2021-01-28 00:59
@ancientTexts-net That tsv has been around for a quite a while. I don't know when  it was created, but it was long  before rc4.

**Comment by ancientTexts-net** [comment] 2021-01-28 16:43
here are the 3 codepoints making up the ZWSP at the end of the origQuote column for xyz8

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/86b26b85-6649-4145-8c89-98b797883c48)

**Comment by ancientTexts-net** [comment] 2021-01-28 16:43
@mandolyte  ^^

looking into it

**Comment by mandolyte** [comment] 2021-02-03 14:00
vi to the rescue... I cloned this repo and switched to the tcc001-tc-create-1 branch. Then I brought up the file in vi and there are *two* zwsp characters at the beginning of the orig quote on row id m2jl:
![image](https://user-images.githubusercontent.com/1289437/106757355-3c23a680-65fe-11eb-9745-ba6baea1b6df.png)

**Comment by mandolyte** [comment] 2021-02-03 14:01
And for row rtc9:
![image](https://user-images.githubusercontent.com/1289437/106757479-61b0b000-65fe-11eb-803f-f2bf6a6dc760.png)

**Comment by mandolyte** [comment] 2021-02-03 14:22
Note: I cannot detect these in either HTML or Markdown modes in tc-create. But they apparently are in memory.

Env 1: using https://develop--tc-create-app.netlify.app/ at v1.1.0-rc.4 build 19-6e50a4c
Test 1: make a change to m2jl not in the orig quote field and save the file. Is it still there?
Result 1: yes, still there. 
Hypothesis: the filters are filtering out the zwsp to/from html, but not updating the in-memory state.

Env 2: same
Test 2: retype the orig quote field in row m2jl and save. Is it still there?
Result 2: No - now gone.
Hypothesis: if you actually update the field with the character it will be corrected... need to test this

Env 3: same
Test 3: add a space in the middle (away from the beginning of cell) and remove it; then save. Is it still there?
Result 3: yes, still there... bummer
Hypothesis: if you copy the entire field and paste it back in the zwsps will be corrected.

Env 4: same
Test 4: copy entire cell and paste it back in; then save. Is it still there?
Result 4: still there. suspect that no change to the value of the field was detected. Note that save button was NOT enabled.
Hypothesis: copy; click out; then paste

Env 5: same
Test 5: copy, delete entire field, click out; save button is enabled now. click in and paste. then save. Is it still there?
Result 5: it is gone.

Conclusion: We have to force the update to the in-memory state in order to eliminate the zwsp characters.

Propose: update the in-memory state to remove all zwsp characters from beginning and end of cell value. NOTE! there may be multiple zwsp characters, not just a single one.

**Comment by mandolyte** [comment] 2021-02-03 14:23
@ancientTexts-net See above testing I did this morning. Do you agree with the proposal?

**Comment by mandolyte** [comment] 2021-02-04 16:43
@cckozie @birchamp @BincyJ @elsylambert @ancientTexts-net 

Zach and I have found a way to fix this. However, "fix" depends on the definition of done. 
- The original description in this issue is about the validator reporting apparently spurious errors about not finding original language quote.
- We determined that the root cause is ZWSP characters in the data that the validator is using (which comes from the in-memory representation), but which the highlighting code ignores or somehow doesn't see/consider.
- We found that we can strip out the ZWSP characters so that the validator doesn't see them and thus will not report these errors.

However, this does not "fix" the data in DCS. So what is the "definition of done"? Is to fix data in DCS? Or is to eliminate the validation errors?

**Comment by cckozie** [comment] 2021-02-04 16:55
@birchamp @BincyJ @elsylambert @ancientTexts-net
I think I'm OK with just fixing it so the validation error does not show up as long as that fix doesn't break other situations where the ZWS is needed but is not processed by the validator (if that situation even exists).

**Comment by RobH123** [comment] 2021-02-04 18:46
What? If we want the CV error not to show up, easier just to remove that check from the CV package. But then, we should write in the file spec for other users of our data: *This field may or may not have (invisible) zero-width spaces in it which any processing software should ignore. (Also take care that these characters don't limit the results of global searches if you're using a general-purpose editor to look at these files.)*

But I guess to go back a step, we do need to answer the above question -- reworded: *Where do the ZWSPs originate and for what reason?* And that would lead to the 2nd related question: *Why do we have ZWSPs in our files, and what purpose do they serve (or what meaning do they have) there?* And perhaps some want to ask the 3rd question: *Who cares anyway?* (That's the only one that I can answer but maybe I'm alone? To be clear: I have absolutely no idea of the answers to the first two questions so that would be very helpful info for me.)

**Comment by ancientTexts-net** [comment] 2021-02-05 16:02
https://git.door43.org/cecil.new/journals/src/branch/master/tc-create-app/tc-create-app.572.md

**Comment by ancientTexts-net** [comment] 2021-02-08 15:11
Should be available in v1.1.0-rc.6 build 21-ad9123a
https://develop--tc-create-app.netlify.app/

@elsylambert , @cckozie 

Thank you :)

**Comment by cckozie** [comment] 2021-02-08 21:22
The validator no longer reports this as an error in v1.1.0-rc.6 build 21-ad9123a

**Comment by elsylambert** [comment] 2021-02-09 04:21
Not seeing this error report by CV in translationCore Create - v1.1.0-rc.6 build 21-ad9123a.

**Closed** 2021-03-04 16:25 UTC
Labels: QA/ElsyTested, QA/KozTested, QA/Passed
