### ISSUE TITLE
Logout and login back gives Username does not exist message

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#15] opened 2019-10-29 15:08 UTC
1. Click on the user icon on the header.
![image](https://user-images.githubusercontent.com/51806180/67779751-7685b780-fa3b-11e9-8b8a-019e464af31f.png)
2. It brings up the below shown screen. Note that the user name is Camel-cased. Actual username is -elsylambert.
![image](https://user-images.githubusercontent.com/51806180/67780129-062b6600-fa3c-11e9-971f-c08ba8df4264.png)
3. Clicking on the logout button, logs me out. and Username and Pwd boxes are enabled with the values in. Those values are incorrect, so if I click on the Login button again, it gives User does not exist or username is invalid message, 
![image](https://user-images.githubusercontent.com/51806180/67780506-8e117000-fa3c-11e9-868b-f32e7970e0b6.png)

**Comment by klappy** [comment] 2019-12-04 20:57
Is this still an issue?

**Comment by elsylambert** [comment] 2019-12-09 15:40
Still an issue in GLtS v0.9.0-alpha.14. The values stored in Point 2 above in the screenshot are not correct.

**Comment by klappy** [comment] 2019-12-16 20:22
This is an odd bug. I'm not exactly sure what is going on but seems to be related to another bug that occurs. From time to time, coming back to GLTS when you are already logged in, you are unable to open a file. It appears as though the saved token is no longer valid, but the local token does still exist on the server.

The complication comes in the situation you documented, when you log out and log back in, it should create a new token, but it is not working for some reason until the browser is reloaded or page refreshed.  

@elsylambert Are you able to confirm that refreshing the page fixes the problem even though it's just temporary to ensure I'm seeing the same bug?

**Comment by elsylambert** [comment] 2019-12-17 15:42
@klappy Yes, refreshing the page fixes the problem.

**Comment by klappy** [comment] 2019-12-30 22:12
A temporary fix for this could be to periodically attempt to access an API endpoint to ensure there is not a 401 error coming back. If a valid result doesn't come back, we can alert the user that we will have to reload the page to fix the problem.

**Comment by mandolyte** [comment] 2020-06-02 13:43
Just tested this with `translationCore Create - v0.9.0-beta.6`. It confirmed an aspect I didn't see discussed above. Namely, if you click the logout button (which is on a model dialog window), then click away, the main window under it is another login - but not a modal dialog window.

Furthermore, the credentials that are filled are correct and work every time I have tried just clicking the login button there.

This suggests that a simple solution is "just close the dialog after the logout button is clicked".

This in turn suggests that we eliminate the modal dialog altogether and just have a drop down menu with a logout option when user clicks their avatar button.

@klappy @birchamp @elsylambert 

Thoughts?

**Comment by mandolyte** [comment] 2020-07-01 13:56
@klappy @BincyJ 

Propose the following to address this issue. 

*Definitions:*
- "logged out state": this means either a) no authentication key exists in indexedDB; 
or b) the authentication object has an empty string for token/sha1 
(and or config/Authorization - it is stored in both places).
- "logged in state": this means that the authentication key exists and the value 
has both username and token values.
- "authentication key": the key "authentication" in the `tc-create-app-state-store`. An example value is below.

*Requirements:*
- If application is started in a logged out state, then if authentication key exists, populate the username field and the value for the `remember me` checkbox. If multiple people use the same device, then it can easily be retyped. The user  must then supply a password and click the button which must have the text "login". If "remember me" is checked then update the token in the authentication object and save it.
- If application is started in a logged out state, and if authentication key does not exist, then present an empty form and let user supply username, password, and optionally check "remember me", then click the login button. Upon successful login, the authentication key is created if it did not exist and is updated if it does.
- If application is started in logged in state, then if "remember me" value is true, then automatically attempt login. If successful, then start at step 2
- If application is started in logged in state, then if "remember me" value is false, populate username; user must supply password, optionally check "remember me", and then click the login button
- If user logs out and "remember me" is true, return to app state 1 with login form populated.
- If user logs out and "remember me" is false, update the authentication object to remove tokens, return to app state 1 with login form populated with username and "remember me" value.


An example value:
```json
{"user":
{"id":13993,
"login":"cecil.new",
"full_name":"",
"email":"cecil.new@gmail.com",
"avatar_url":"https://bg.door43.org/avatars/f8a86db8b875c63428a3d89dae47cf84",
"language":"","is_admin":false,"last_login":"2020-06-24T13:16:03Z",
"created":"2019-09-19T13:37:42Z",
"username":"cecil.new"
},
"token":
{"id":5552,
"name":"tc-create-app",
"sha1":"e3c0270c43d8de252a9c92c61660ca11c7d98623",
"token_last_eight":"c7d98623"},
"config":
{"server":"https://bg.door43.org",
"tokenid":"tc-create-app",
"headers":
{"Content-Type":"application/json",
"Authorization":
"token e3c0270c43d8de252a9c92c61660ca11c7d98623"}
}
,"remember":true
}"
```

**Comment by mandolyte** [comment] 2020-07-02 14:50
After a brief discussion with @klappy this is how I am going forward:
- move code in Authenticate.js into the custom hook useAuthentication.js; note that the former has similar functions (they are duplicative).
- remove the former as it will no longer be needed.
- expose new actions that will allow developers to use the code without the UI components, namely, login, logout, update? -- where "update" may simply invoke a closure from the using app to persist ("remember me")
- remove the demo page as well for Authentication.
- the custom hook will now return a Login component, not an Authentication component
- make a new demo for the custom hook

**Comment by mandolyte** [comment] 2020-07-03 11:25
@klappy (sorry to keep adding to the things I want you review! enjoy your day off)

It occurred to me that even if we remove the auth persistence in GRT, we could still configure the Auth Context with app level persistence functions, passed as closures. If GRT must pass authentication with every API call, then at least it needs a "get auth" to obtain the app's persisted credentials.

Thoughts?

**Comment by elsylambert** [comment] 2020-07-07 19:00
@mandolyte Can this be tested in an RCL? Please post the link here.

**Comment by mandolyte** [comment] 2020-07-07 20:01
Yes, at: https://deploy-preview-40--gitea-react-toolkit.netlify.app/#/Authentication%20?id=authenticationcontext

I will begin to integrate into tc-create-app tomorrow. Which may result in further changes... 

@elsylambert

**Comment by elsylambert** [comment] 2020-07-08 20:32
@mandolyte Authenticate Form looks good but the login form does not function properly. I entered UN and PWD but the sign In button did nothing upon clicking.

**Comment by mandolyte** [comment] 2020-07-09 12:04
Here is what you should see...
This image is first; my credentials are being inserted by LastPass. If you are not using a password manager, the Username and Password should be empty.
![image.png](https://images.zenhubusercontent.com/5e8cb99214ac08760f0cb72b/0762236c-bf51-47f0-b879-a24ea3700eda)

When you supply the u&p, you will see the same form, but now for logging out. Like this:
![image.png](https://images.zenhubusercontent.com/5e8cb99214ac08760f0cb72b/4e2324bc-18ae-4431-8288-0b102aacdddb)

If you check "keep me logged in", then you won't see much difference. That checkbox will persist the login token so that an app like tc-create can skip the login since you are still logged from last login. If left unchecked, then each time you start the app, you need to supply u&p.

Does this match what you see?
https://deploy-preview-40--gitea-react-toolkit.netlify.app/#/Authentication%20?id=authenticationcontext

@elsylambert @klappy

**Comment by elsylambert** [comment] 2020-07-09 14:03
Works fine as per @mandolyte comments. Seeing the expected behaviour in GRT.

**Comment by ancientTexts-net** [comment] 2020-07-11 07:16
Found a weird bug when we deployed to `develop`.

It looks like the IndexedDB format for `keyvaluepairs` / `authentication` changed in the most recent updates to `tc-create-app`.  That's causing incompatibility (crash) if a user had the **old** style `authentication` value.

Looks like in the *old* style, the value was marshaled as a string (stringified object);
while in the *new* style, the value is stored as a proper object.

OLD:
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/e16fccb3-e38a-4a93-88cb-42562a06d4bf)

NEW:
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/d947b17b-fca1-4bff-bc07-c4c73db86587)

**Comment by elsylambert** [comment] 2020-07-13 14:51
Looks good in translationCore Create - v1.0.0-beta.8. After the user logs out, the password field is empty, and after entering the password , user can log back in without seeing the "Username does not exist" message.

Written up #198 for a finding during testing this issue.
Since, this issue fixes the original problem, I am passing this issue.

**Closed** 2020-07-15 17:11 UTC
Labels: QA/Passed, bug
