### ISSUE TITLE
Validate Source text on open

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#818] opened 2021-04-16 21:03 UTC
Issue:
---
In order to ensure that the user can continue to work the initial validation check must be done on the source side as we are already doing on the target.   Errors in source side should say: 
"tC Create is unable to continue. The master data has the following error: duplicate ID(s) <IDs>."
"tC Create is unable to continue. The master data has the following error: <bad header error>."
"tC Create is unable to continue. The master data has the following error: <bad number of columns error>."

"Please take a screenshot and contact your administrator." 

DoD:
---
On Open validation is run against both the source and target files. 

Details:
---

Field reported by Larry S.
movie here: https://drive.google.com/file/d/1CgS3NKv5TfR7Qo4XFsKnitTR6udfiJMi/view?usp=sharing

Follow these steps to reproduce the problem:
1. Delete the Luke tN file from your user's repo
2. Log in to tC Create using that users credentials
3. Select the Luke tN project
4. Verify that the app is set for 25 rows/page
5. Use the Next Page button to page forward until you get to rows 1076-1100
6. Scroll down until you get to ID l400 (lower case L)
7. Open the Columns modal and show all columns
8. Change the SupportReference field on row l400 to some other text including "l400" in that text (I used Testing l400)
9. Click out of the SupportReference field and wait for the UI to catch up
10. Click the Next Page button to go to the next page
11. After it pages forward, click the Previous Page button to go back to the page you were on 
12. Scroll down to the l400 row
13. Notice that the SupportReference field is now back to what it was before you changed it
14. Scroll up 1 row to l365
15. Note that the text you entered for row l400 is now in row l365
16. Click the Save button
17. After the save is complete, click the button to go to the file in the repo
18. Go into edit mode in the repo and scroll down to line 1100
19. Note that the data has been saved to the wrong row as it was displayed after paging forward and back
In my testing it seems that it only fails after row 1100, but it does fail consistently.

**Comment by elsylambert** [comment] 2021-04-19 04:28
I was able to replicate this issue with the steps mentioned above. The data was wrongly written on the row above as reported in the issue. However, I was able to do so only in Luke.  I tested Acts, Rev, Jer, Psalms, Proverbs, Genesis and few other big books but none of them showed this behaviour.

Luke has 4490 rows, Psalms has 5219 rows, but only Luke shows consistently bad behaviour after 1100 rows.

**Comment by mandolyte** [comment] 2021-04-20 13:17
Found a quicker way to reproduce the problem.
*Variation 1*
Let's use the search function to pull up row l400 and change that way.
- delete branch
- go back to Luke
- add ID column
- click search and enter l400
- make the change
- the search function will now show both rows (since "l400" now occurs on both rows)
![image](https://user-images.githubusercontent.com/1289437/115402205-33804c80-a1b9-11eb-849c-9b2feb1d0b9b.png)

**Comment by mandolyte** [comment] 2021-04-20 17:42
Problem turns out to be a data issue, namely, there are two consecutive rows with the same row ID (`r11g`) for the same verse.

Here is the raw data:
```
LUK	7	18	r11g	writing-newevent	ἀπήγγειλαν Ἰωάννῃ οἱ μαθηταὶ αὐτοῦ περὶ πάντων τούτων	1	his disciples reported to John concerning all these things	This sentence introduces a new event in the story. Alternate translation: “the disciples of John told him about all these things” (See: [[rc://en/ta/man/translate/writing-newevent]])
LUK	7	18	r11g	writing-newevent	οἱ μαθηταὶ αὐτοῦ	1	his disciples	The term **his** refers to John the Baptist, not to Jesus. Alternate translation: “the disciples of John” (See: [[rc://en/ta/man/translate/writing-newevent]])
```

The code that does the "correlation" of the source and target is discarding one of the rows.
This was confirmed by manually changing the file in QA master so that one of the rows had `r12g`, eliminating the duplicate.

Since the on-open validation is already checking each row of the file for how many cells there are, a bit of logic could be inserted to keep track of the IDs. This logic would need:
- to know which column contains the ID. **I know how to do this.**
- to know whether IDs are unique in the file or by verse; **I don't know which is true. So need this answer.**

Like the other on-open validations, it needs to prevent the user from opening the file, because data is being lost if it gets that far.

**Comment by mandolyte** [comment] 2021-04-22 12:01
###Notes for 2021-04-22### 
The target context provider is created largely from a useFile hook. This hook takes as input the source file content, which if the target file does not exist yet, it will be created with the source content as the default content.

This means we have the following scenarios:

1. Target file does not exist
2. Target file does exist

Test: if target does not exist and source has a defect, then does anything get created in the target?

1. delete branch cecil.new-tc-create-1 in QA DCS `unfoldingword/en_tn`
2. edit the book of Jude by removing the header row. Submit patch as a PR. The approve PR and squash merge and delete my patch branch.
3. Check and confirm master changed. -- confirmed
4. Now use tc-create to edit this file
5. The validation error properly shows, however, the branch is created and the damaged file is created as well.

**Implication** the on-open check needs to be moved to the useFile hook.
fyi... @birchamp @ancientTexts-net

**Comment by mandolyte** [comment] 2021-04-22 13:04
### Solution Design

**Concept** add a new optional onOpenValidation function parameter to the `useFile()` function in gitea-react-toolkit. If provided, then the content of the file will be passed to this function for validation. In addition, the `useFile()` function will return a new property as part of the state object. The new property will be an object containing two properties: a boolean indicating pass/fail of the validation and an array of error messages.

**Scenarios**
1. If no validation function is provided, then the state validation property will be null or undefined.
2. If validation function is provided and the validation passes, then the object will return a value of true for the `valid` property and an empty array for the messages property.
3. If validation is function provided and the validation fails, then the object will return a value of false for the `valid` property and the messages array will list all the errors found. The format of the messages will be completely determined by the validation function provided.

**Notes**
- Existing code that does not provide the new validation parameter will not need to be changed; nor does it need to capture the validation state return value.
- Code that needs to validate the content must provide the new function to `useFile()` and it must examine the return value in order properly act on it.

The plan is to split the current on-open validation logic into two parts:
- The part that updates state of the app must remain in the app
- The part that is pure code looking at content will be moved to GRT itself to make it re-usable.

At the moment, TN (both 9 and 7 column versions) and TWL are targeted for on-open validation for a total of three formats. While superficially the checks are the same, they are each unique. The checks are:
1. Does the file have the correct header row?
2. Does each row in the file have the correct number of columns?
3. (new) Are there duplicate row IDs within chapter/verse?

**Comment by mandolyte** [comment] 2021-05-03 14:35
@cckozie @elsylambert @ancientTexts-net @BincyJ Since @birchamp is out, wondered if you had any thoughts on whether I should change the on open validation dialog for the target. Here is the new source side dialog with the text suggested in DoD:
![image](https://user-images.githubusercontent.com/1289437/116890011-30df1780-abfb-11eb-83ba-b2fd9991ecd8.png)

And here is the current dialog for the target:
![image](https://user-images.githubusercontent.com/1289437/116890132-481e0500-abfb-11eb-859f-61587722c76e.png)

**Comment by elsylambert** [comment] 2021-05-03 15:54
@mandolyte Here is my suggestion : The message title should have mention of the Source/Target file, that will give a clear idea to the user where to look the error for. For e.g 
"This file cannot be opened by tC Create as there are errors in the Master file. Please contact your administrator to address the following error(s)"

"This file cannot be opened by tC Create as there are errors in the target file. Please contact your administrator to address the following error(s)"

**Comment by BincyJ** [comment] 2021-05-03 17:03
I agree with @elsylambert. @birchamp ^^

**Comment by mandolyte** [comment] 2021-05-03 17:41
Thanks! I have this change and the new check for duplicate row IDs
remaining on this issue to do.


Cecil

**Comment by mandolyte** [comment] 2021-05-04 15:04
Testing hints... in QA DCS, in org unfoldingword, repo en_tn, I edited the tN for COL: I copied a row ID and pasted it over the top of other row ids in the file. Then did the PR thing and over wrote master.

Here is the error for what I did to the source (master):
![image](https://user-images.githubusercontent.com/1289437/117024907-6aca1f80-acc8-11eb-9849-b24f3a145bce.png)

**Comment by mandolyte** [comment] 2021-05-04 15:07
Testing hints... in QA DCS, unfoldingword/en_tn, I first used tc-create against 1TH, then backed out. I only did this in order to create my branch. I then edited the branch copy in DCS by copying a row id into several places thru out the file; then committed the changes directly to my branch.

Then in tc-create, I brought up 1TH. This will show the dups:
![image](https://user-images.githubusercontent.com/1289437/117025422-e62bd100-acc8-11eb-9e98-3c0418c28380.png)

**Comment by ancientTexts-net** [comment] 2021-05-06 14:14
https://deploy-preview-58--markdown-translatable.netlify.app/#/Translatable?id=translatable-1

@mandolyte ready to review again please thank you :))

**Comment by ancientTexts-net** [comment] 2021-05-11 05:59
v1.2.1-rc.1 build 50-1bb4a08
https://develop--tc-create-app.netlify.app/

**Comment by elsylambert** [comment] 2021-05-11 15:21
translationCore Create - v1.2.1-rc.1 build 50-1bb4a08.
Tested Source Text validation On-Open: 
- When Master file has duplicate ids, the validator throws the following message, which works as expected:
![Screen Shot 2021-05-11 at 9.22.07 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d5085b6d-1558-491a-a8ea-08ef3914c0db)
If the file has error on Source as well as Target, it shows the error from the Source/Master file and gives the user the option to only report the problem to the admin and close. At this point, this is the limitation as the user does not have control over the Master file, which is in line with the permissions. So the Master file error takes precedence over the target file. This is working fine.

If the file has error in the target side, the following message is displayed :
![Screen Shot 2021-05-11 at 11.12.43 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2c9cb27f-681e-4260-84d5-2d67a8111aa2)

This works as expected.

**Comment by cckozie** [comment] 2021-05-11 20:44
v1.2.1-rc.1 build 50-1bb4a08
The app properly finds the duplicate ID's, but the row number specified at the end of the statement "is a duplicate of the ID on row nnn" is off by one. In the first noted line, the row should be 896, not 895. All reported duplicate ID's have that same problem.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/e646b97a-4e74-43a3-99d6-fd251b2420ed)

**Comment by mandolyte** [comment] 2021-05-12 14:26
@cckozie I added the multiple errors on purpose in order to help the admin fix the problem. It now shows:
- what is expected
- what was found
- the first character that differs from what was expected, including the hexadecimal, so that those CR type characters will show someting.

If you don't see value in these, I can comment them out. But I do want to leave them in the code for next time I have to find some invisible character.

@ancientTexts-net thoughts?

**Comment by BincyJ** [comment] 2021-05-12 15:14
@mandolyte to add the character limit logic to the header error message.

**Comment by cckozie** [comment] 2021-05-12 18:22
I found another problem that I think the on-open validator should catch, and that is missing ID's. The attached file has two rows in which incorrect tabs make it look like the ID is blank/missing. The validator reports this as a duplicate which is technically correct, but I think "missing" is more accurate. Writing this up in a new issue rather than failing this since it was not in the DoD.

[https://app.zenhub.com/files/191973535/dbac502e-7219-4471-b4be-9e435ec3e562/download](https://app.zenhub.com/files/191973535/dbac502e-7219-4471-b4be-9e435ec3e562/download)

**Comment by ancientTexts-net** [comment] 2021-05-13 10:18
`v1.2.1-rc.2` build 52-944acd1

https://develop--tc-create-app.netlify.app/

@elsylambert @cckozie

**Comment by elsylambert** [comment] 2021-05-13 19:22
translationCore Create - v1.2.1-rc.2 build 52-944acd1
On-Open Source Validator:
- Reports error due to duplicate IDs with correct row numbers.
- Reports header missing on target file with appropriate message.
- Reports columns missing on Target file.

**Comment by cckozie** [comment] 2021-05-13 21:41
@birch - If the source file has duplicate ID's, the validator does not report any target file problems until the source file problems are fixed. Are you OK with that, or do you want the on-open validator to display all errors in both the source and target files?

**Comment by elsylambert** [comment] 2021-05-14 00:23
If the Source file has duplicate IDs, two scenarios here:
1. If a file/book is opened for the first time(no target file in the branch) and duplicate IDs are detected in the Source file, then the target file is not created at this point. So Source side On-Open Validation is fine.

2. If there is an existing Target file with the duplicate ids that was previously copied from the Source, are in the branch, the validator first reports Source side only.  This is what @cckozie  pointed out in his comment. 
@birchamp

**Comment by cckozie** [comment] 2021-05-17 18:36
Per @birchamp, I created a new issue (#866) for the problem of not testing both the source and target if the source contains errors.

**Closed** 2021-08-10 18:00 UTC
Labels: bug, QA/Passed, Priority/Critical, demoed, Field Reported, QA/ElsyTested, QA/KozTested
