### ISSUE TITLE
tcc crashes opening unfoldingWord/en_twl/en_SNG.tsv

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/tc-create-app#1599] opened 2023-06-22 19:39 UTC
### User Story

tcc crashes opening unfoldingWord/en_twl/en_SNG.tsv

I was able to reproduce this on my PC. There is a crash in the console:

![Screenshot 2023-06-22 at 3.17.37 PM (2).png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/97f9425a-d52b-4eb5-9dee-8bdce5d2e5d9)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by birchamp** [comment] 2023-06-30 20:07
this is a duplicate of #1596

**Closed by birchamp** 2023-06-30 20:07 UTC
Labels: duplicate
