### ISSUE TITLE
Incorrect line breaks in raw mode

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord/tc-create-app#53] opened 2020-01-10 19:55 UTC
Duplicate of #48

upLooking at TA/translate/figs-metaphor/01.md

In preview mode, breaks are OK now. However, in raw mode they still seems to occur in text that has underlining. See the Bible quotes in the section `Examples from the Bible`

> Listen to this word, 
you cows of Bashan
, (Amos 4:1 ULT)

**Comment by birchamp** [comment] 2020-01-14 16:53
This is a duplicate of #35

**Comment by klappy** [comment] 2020-02-10 18:19
Duplicate issue was addressed and closed.

**Closed by klappy** 2020-02-10 18:19 UTC
Labels: duplicate
