### ISSUE TITLE
upgrade to the new Content Validator

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#786] opened 2021-04-07 15:49 UTC
Update tCC to handle the calls to the new Validator and confirm TWL compatibility

**Comment by ancientTexts-net** [comment] 2021-04-21 12:46
ready for testing

https://develop--tc-create-app.netlify.app/
translationCore Create - `v1.2.0-rc.4 build 33-43fd9f5`

**Comment by cckozie** [comment] 2021-04-26 17:48
Is this testable? 
The icon button to run the validator is not being displayed in tWL projects. Is there a way to test it in tN projects?

**Comment by elsylambert** [comment] 2021-04-26 22:38
@ancientTexts-net ^^

**Comment by mandolyte** [comment] 2021-04-27 02:00
It would only be testable if you knew of checks or messages that have been
updated.

**Comment by cckozie** [comment] 2021-04-27 14:38
It appears to be working correctly in v1.2.0-rc.5 build 34-ab649d5. My validator shows only a few differences from the previous version, and those appear to be caused by updates that have fixed content problems.

**Comment by elsylambert** [comment] 2021-04-29 04:05
v1.2.0-rc.6 build 37-1f07640. I am seeing error-450 "Resource container link should have '*' language code"again in the CV files which was earlier fixed by #630 and #637. 
@mandolyte 
![Screen Shot 2021-04-29 at 12.00.51 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/fee4455b-0195-4a42-8acd-a3614bf1b010)

**Comment by ancientTexts-net** [comment] 2021-04-29 14:46
@RobH123 

We believe this issue was solved last time by using the `suppressNoticeDisablingFlag`: true

Can you advise us -- how can we silence these errors for tN now please?

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/12877aa8-9a85-4db2-a486-5f6c3ebc8ed2)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/eb771718-4a9a-432a-b507-fe7690935e52)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/be6b29d8-33dd-449a-b3ba-9a5aa029f73f)

**Comment by RobH123** [comment] 2021-04-29 19:50
Oh, looking back I see that flag name is ambiguous: is it suppress(NoticeDisabling)Flag or (suppressNotice)DisablingFlag? Maybe it should be made positive in the next version upgrade, i.e., enableNoticeDisablingFlag -- I think that's less ambiguous. I think I changed some other flag names to remove confusion but missed that one.

Anyway, it's current the first of the above, i.e to supress the disabling of notices, set it to false I think @ancientTexts-net 

    if (!checkingOptions?.suppressNoticeDisablingFlag) {
        cmtResult.noticeList = removeDisabledNotices(cmtResult.noticeList);
    }

**Comment by ancientTexts-net** [comment] 2021-04-29 21:38
src/components/translatable/TranslatableTSV.js

Line 184 

Thank you

**Comment by ancientTexts-net** [comment] 2021-04-30 10:38
https://develop--tc-create-app.netlify.app/
v1.2.0-rc.8

**Comment by elsylambert** [comment] 2021-04-30 22:06
v1.2.0-rc.8 build 40-f9678ab.
Content validator looks good. Not seeing 450 error. Tested a few books in OT and some in NT, not seeing unexpected errors.

**Comment by ancientTexts-net** [comment] 2021-05-02 03:00
@elsylambert @cckozie Does it look like we're ready to move this card down the lanes now? Thank you

**Comment by cckozie** [comment] 2021-05-03 13:23
I'm no longer seeing the 450 errors in v1.2.0 build 41-eb23e86.

**Closed** 2021-08-10 18:33 UTC
Labels: QA/Passed, QA/ElsyTested, QA/KozTested
