### ISSUE TITLE
Filter view crashes the parallel scripture and the edit side as well

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#68] opened 2020-02-04 15:35 UTC
Alpha-26.
- Open book of Ruth. Now at chapter 1 of the book.
- From the filter select Chapter 2.
- The parallel scripture does not load up and the edit side screen is blank. See the snapshot.
![Filter selection.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d000c041-0a5a-4efe-a703-95eb9bcb3c96)

**Comment by klappy** [comment] 2020-02-04 19:10
This appears to be due to the weird login bug. Somehow the app thinks you are logged in but the server doesn't.

**Comment by klappy** [comment] 2020-02-06 14:23
This appears to be caused by having an out of date branch/fork that is behind master and the master has different rows by chapter/verse/id combination that is not found in both the master branch and your copy. 

The short term fix for this is to follow the proposed branch workflow and cleanup your branch/fork before each editing session is done, to ensure that you have the latest in sync data to master.

What we can do to address this specific bug is to rewrite the filtering logic, which is already needed to address the duplicate text in each filter option.

**Comment by klappy** [comment] 2020-02-07 16:24
@birchamp: The Editing/Branch workflow will likely supercede this. I recommend that we wait until that is implemented to address this. It may already be taken care of once we get around to it.

**Comment by klappy** [comment] 2020-02-07 21:32
There are notes/rows in one of three states causing duplicates:
1. notes/rows that exist in both source and target.
1. notes/rows that only exist in source.
1. notes/rows that only exist in target.

Could this information be used to help us filter data that is only in the source, only in the target?

**Comment by birchamp** [comment] 2020-02-11 19:34
@klappy Yeah, let's wait until Branch WF is done. I'll pull this out of the sprint

**Comment by klappy** [comment] 2020-02-13 19:11
Addressed along with #44.

**Comment by elsylambert** [comment] 2020-02-28 15:39
Not seeing the issue in v0.9. beta-4. Filter view is looking good.

**Closed** 2020-03-06 18:17 UTC
Labels: QA/Passed
