### ISSUE TITLE
Existing file gets overwritten on first creation of a branch

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#208] opened 2020-07-16 01:26 UTC
https://bg.door43.org/Elsy-org-test/ru_ta already has the majority of the files in Russian
1. Choose Elsy-org-test as your org
2. Choose TA
3. Choose Russian
4. Open a md file like /translate/figs-metaphor/01.md
5. The Russian will be overwritten in English in your branch. 

In other words, when the branch gets created, an English file is copied to the branch even if the master contains the file. 
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/30831e0d-5216-4b4f-bb63-42ae6c05d9c3)

**Comment by elsylambert** [comment] 2020-07-16 14:09
@birchamp I can replicate the issue. After I deleted my branch, opened ru_ta for figs-ellipsis(for this file a Russian translation exists), it showed English on Target side![Screen Shot 2020-07-16 at 10.09.37 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/444b2a0b-a900-4a1b-bd07-504969c1fdf5)

**Comment by elsylambert** [comment] 2020-07-17 15:35
Added #223 for tN issue related to this same issue.

**Comment by elsylambert** [comment] 2020-07-20 11:55
Verified on translationCore Create - v1.0.0-rc.2. The issue is fixed with existing file getting overwritten on first creation of branch. Able to see the language translation on the Target side.

**Closed** 2020-07-29 16:37 UTC
Labels: Priority/Critical, QA/Passed, bug
